= 개요 INTRODUCTION
37signals
:doctype: article
:encoding: utf-8
:lang: ko
:toc: left
:numbered:

== Getting Real이란?
성공적인 웹 애플리케이션을 만들고 싶으세요? 그렇다면 현실적(Get Real)이어야 합니다. Getting Real은 더 작고, 더 빠르며, 더 나은 소프트웨어를 만드는 방법입니다.

* Getting Real은 실재를 표현하는 도구(차트나 그래프, 박스, 화살표, 도식, 와이어 프레임 등)는 건너뛰고, 진짜 제품을 만듭니다.
* Getting Real은 작습니다. 집단, 소프트웨어, 기능, 서류 작업 등에서 필수가 아닌 모든 것을 줄입니다. (여러분이 필수적이라고 생각하는 대부분은 실제로 그렇지 않을 겁니다.)
* Getting Real은 작음을 지속하며, 기민함(agile)도 유지합니다.
* Getting Real은 사용자가 사용할 실제 화면의 인터페이스부터 시작합니다. 사용자들의 실제 경험에서 시작하여 시스템 쪽으로 구축해 갑니다. 그러면 소프트웨어가 잘못 만들어지기 전에, 올바른 인터페이스를 얻을 수 있습니다.
* Getting Real은 반복적(iteration)이며, 변경 비용을 낮추는 방식이기도 합니다. Getting Real은 출시, 수정, 끊임 없는 발전을 거듭하는 웹 기반 소프트웨어에 대해 가장 완벽한 접근 방법입니다.
* Getting Real은 고객에게 정말로 필요한 것들만 제공하고, 나머지는 제거합니다.

=== Getting Real의 이점들
Getting Real은 여러분에게 더 좋은 결과물을 제공합니다. 여러분이 어떤 문제에 봉착했을 때 그 문제에 대한 아이디어를 머릿속에서 고민하기보다는, 진짜 문제를 다루게 하기 때문입니다. 즉, 현실적이 될 수밖에 없습니다. +
Getting Real은 기술 명세서나 걸핏하면 수정되는 문서들보다 먼저 진짜 화면을 만듭니다. 기술 명세는 합의한 환상이지만 실제 웹 페이지는 현실이기 때문입니다. 이 웹 페이지야말로 사용자가 실제로 보고 사용하는 것입니다. 이것이야말로 정말 중요한 부분입니다. Getting Real이 여러분을 더 빨리 목적지로 인도할 겁니다. 다시 말해, 여러분은 추상적인 개념이 아닌 실제 결과물을 가지고 판단하면서 소프트웨어를 만들어낼 수 있습니다. +
마지막으로 Getting Real은, 웹 기반 소프트웨어에 가장 어울리는 접근 방법입니다. 과거에는 소프트웨어를 상자에 넣어 보내고, 업데이트하기까지 1년이나 2년이 걸렸습니다. 인스톨 기반의 소프트웨어와 달리, 웹 애플리케이션은 매일매일 끊임 없이 개선할 수 있습니다. Getting Real은 이런 장점을 극대화해줍니다.

.살아 있는 소프트웨어를 만들려면…
[TIP]
====
생동감 있는 문장은 간결하다. 문장에 불필요한 단어가 들어가지 않고, 문단에도 불필요한 문장이 없다. 같은 이유로, 도면에도 쓸데 없는 선이 있으면 안 되고, 기계에도 쓸데 없는 부품이 있어선 안 된다. 이는 저자가 문장을 무조건 짧게 만들거나 자세한 설명은 하지 않고 주제를 뭉뚱그려서 달성할 수 있는 것이 아니라, 모든 단어가 말하게 함으로써 가능해진다.

윌리엄 스트렁크의 <http://www.aladin.co.kr/shop/wproduct.aspx?ItemId=1002280&start=slayer[영어 글쓰기의 기본(The Elements of Style)]>에서
====

=== 비대화는 그만
장황하고, 관료적이고, ‘우리에게 발생할 만한 모든 문제를 해결하는’ 프로세스와 같은 낡은 방식으로는 흔히, 평범함으로 꽉 차있는 비대하고 잊혀지는 소프트웨어가 만들어집니다. 으엑!

=== Getting Real이 없애는 것들
* 몇 개월이나 몇 년이 걸리는 긴 일정
* 믿을 수 없는 기능 명세
* 점점 커지는 논쟁
* 끝없는 회의
* ‘필요’라는 이름으로 고용된 많은 인원
* 무의미한 버전 번호들
* 완벽한 미래를 그린 초기의 로드맵
* 끝없는 환경 설정 옵션
* 외주 고객 지원
* 비현실적인 사용자 테스트
* 쓸데 없는 서류 작업
* 탑다운 방식의 위계 질서

훌륭한 소프트웨어를 개발하는 데 무지막지한 돈이나 거대한 팀 또는 기나긴 개발 주기는 필요 없습니다. 그런 것들에서는 대체로 느리고, 불편하고, 따분한 애플리케이션이 만들어집니다. Getting Real은 반대입니다.

=== 이 책에서 우리는 이런 내용을 다룰 것입니다
* 철학의 중요성
* 작은 규모가 왜 좋은지
* 더 작게 만드는 방법
* 아이디어를 재빨리 현실화하는 방법
* 팀을 구성하는 방법
* 디자인을 철저히 해야 하는 이유
* 글쓰기가 중요한 이유
* 경쟁을 해야 하는 이유
* 애플리케이션을 홍보하고 입소문을 타게할 방법
* 성공적인 고객 지원의 비밀
* 출시 후에도 동력을 유지하는 방법
* 그 외 다수

이 책은 큰 그림을 그리는 아이디어에 초점을 맞추고 있습니다. 구체적인 코드나 CSS 트릭 같은 수렁은 피할 것입니다. Getting Real 프로세스를 이끄는 주요 아이디어나 철학에만 초점을 맞추겠습니다.

=== 이 책이 여러분한테 적합한 책일까요?
여러분은 좋은 아이디어를 구현하고자 애쓰고 있는 창업가나 디자이너, 프로그래머, 기획자, 마케터입니다. +
여러분은 종래의 규칙을 더 이상 적용할 수 없다는 점을 실감합니다. 해마다 시디롬으로 소프트웨어를 배포하고 있습니까? 2002년에 출시한 버전이 몇 개나 되나요? 이것들로부터 떠나세요. 여러분은 개발, 출시, 수정만 반복해야 합니다. +
여러분은 애자일(agile) 개발 방법론이나 비즈니스 구조를 아직 확립하지 못했지만, 더 알고 싶어하는 사람입니다.

*여러분이 이런 사람이라면, 이 책은 여러분을 위한 책입니다.*

[NOTE]
====
이 책은 주로 웹 애플리케이션 구축에 초점을 맞추지만, 여기에 등장하는 많은 아이디어는 소프트웨어가 아닌 분야에 적용해도 됩니다. 작은 팀, 신속한 프로토타이핑, 반복 추정 같은 개념들은 여러분이 비즈니스나 집필, 웹 디자인, 음반 녹음 외에도 다양한 분야에서 일을 시작하려고 할 때 좋은 지침이 될 것입니다. Getting Real을 삶의 한 영역에 적용해본다면, 이 개념이 얼마나 넓은 영역에까지 적용될 수 있는지 알게 될 것입니다.
====

== 37signals 소개
=== 하는 일
37signalsfootnote:[(옮긴이) 2014년 2월 5일, 37signals는 회사 이름을 Basecamp로 바꾸고, Basecamp와 Campfire를 제외한 제품군을 정리하였다. 자세한 이유에 대해서는 http://37signals.com/의 글을 참고하기 바란다.]는 간명하게 하나의 문제에 초점을 맞춘 소프트웨어를 개발하는 작은 조직입니다. 우리가 만든 제품은 협업이나 조직 관리에 도움을 줍니다. 35만명이 넘는 개인, 작은 조직들에서 우리가 만든 웹 애플리케이션을 활용하고 있습니다. ‘월스트리트 저널’의 제러미 웨그스테프(Jeremy Wagstaff)는 “37signals의 제품은 아름답고 우아하며 직관적으로 사용할 수 있는 간명한 도구이며, 아웃룩 화면을 마치 고문실 같이 느끼게 만든다.”라고 평가했습니다. 우리 제품이 여러분을 고문대에 올리는 일은 없을 겁니다.

=== 일 처리 방식
우리는 요즘 소프트웨어가 너무 복잡하다고 생각합니다. 너무 많은 기능, 너무 많은 버튼, 게다가 배워야 할 내용도 너무 많습니다. 우리 제품에서는 일부러 기능을 줄였습니다. 더 똑똑하게, 더 편하게, 여러분만의 방식대로 일을 처리할 수 있고, 사용하기도 쉬운 제품을 만듭니다.

=== 우리의 제품
우리는 이 책의 출판 시점에 다섯 개의 제품을 판매하고 한 개의 오픈 소스 웹 애플리케이션 프레임워크를 개발하고 있습니다.

* Basecampfootnote:[http://basecamphq.com/]는 프로젝트 관리 기법을 완전히 뒤바꿉니다. 간트 차트나 예쁜 그래프, 숫자로 뒤덮힌 스프레드시트 대신, Basecamp는 메시지, To-do 리스트, 간명한 일정표, 협업 문서 작성 및 파일 공유 기능을 제공합니다. Basecamp가 더 나은 방식이라고 수십 만의 사용자가 인정합니다. Salon.com의 페하드 매자웃(Farhad Manjoo)은 “Basecamp는 웹 소프트웨어의 미래를 대표합니다.”라고도 말했습니다.
* Campfirefootnote:[http://campfirenow.com/]는 단순한 비즈니스용 그룹 채팅 툴입니다. 지속적인 실시간 그룹 채팅이 얼마나 가치있는지를 이해하는 기업들이 증가하고 있습니다. 기존 메신저는 일 대 일 대화를 하기엔 적합하지만, 세 사람 이상이 대화를 나누기에는 끔찍합니다. Campfire는 이 문제와 함께 다른 수많은 문제들도 해결했습니다.
* Backpack은 “간단한 25단계로 삶을 체계화하세요”라고 말하는 혼란스럽고 복잡한 개인용 정보 관리 도구들의 대안입니다. Backpack의 간명한 페이지, 노트, 할 일 목록, 휴대폰/메일 기반의 알림 기능은, 현재 상황에 피로를 느끼는 분들을 위한 새로운 아이디어입니다. 월스트리트저널의 토마스 웨버(Thomas Weber)는 ‘태스크 관리 소프트 중 최고’라고, 뉴욕타임스의 데이비드 포그(David Pogue)는 “매우 쿨한” 조직 관리 툴이라고 말했습니다.
* Writeboard는 혼자 혹은 다른 사람과 함께 글을 쓰고 공유하고 고치고 비교할 수 있는 도구입니다. 지금까지의 번잡한 워드프로세서를 대신하는 새로운 문서 작성 도구입니다. Daring Fireball의 존 그루버(John Gruber)는 “Writeboard는 내가 본 것 중 가장 알기 쉽고 간단한 웹 애플리케이션이다”라고 말했으며, 또 웹의 전도사로서 알려진 제프리 젤드만(Jeffrey Zeldman)은 “37signals가 또 해냈다!”라고 찬사했습니다.
* Ta-da List는 할 일 목록을 다른 사람과 함께 관리하는 온라인 애플리케이션입니다. 개인용 또는 공용 목록을 만들어 다른 사람과 쉽게 협업할 수 있습니다. 태스크 관리에 이보다 더 쉬운 방법은 없습니다. 할 일 목록은 십만 개를 넘어섰고, 태스크는 백만 개를 넘습니다.
* Ruby on Rails는 개발자를 위한 풀 스택 오픈 소스 웹 프레임워크입니다. 루비로 작성되었으며 실제 애플리케이션을 빠르고 쉽게 개발할 수 있습니다. 레일스는 여러분이 아이디어에 전념할 수 있도록 잡다한 일을 처리합니다. O’Reilly 출판사의 나단 토킹턴(Nathan Torkington)은 “Ruby on Rails는 놀랍습니다. 쿵후 영화에 비유하자면, 여러 개의 바쁜 프레임워크들이 작은 신참자를 때려 주려고 준비했지만, 오히려 신참자가 다양하고 참신한 공격으로 그들을 때려주는 장면 같습니다.”라고 말했습니다.

다른 제품과 회사에 대한 자료는 http://www.37signals.com[www.37signals.com]footnote:[(옮긴이) 이 글을 번역하는 시점에 http://37signals.com에는 사명 변경과 서비스 집중에 대한 공지글만 존재한다. 새 회사의 홈페이지는 http://basecamp.com/이다.]에서 확인하세요.

== 비관론자들께 미리 말씀드린다면...
본문에 들어가기 전에 앞서 Getting Real에 대해 자주 듣는 불만 사항들을 먼저 짚고 넘어가고자 합니다.

=== 이 방법은 우리에게 적합하지 않습니다
Getting Real은 37signals의 조직에 꼭 맞는 시스템입니다. 다시 말해, 세상 모든 프로젝트에 적용할 수 있는 아이디어는 아닙니다. 여러분이 무기 시스템이나 핵 발전 시설, 몇 백만 명이 사용하는 은행 시스템, 생명이나 돈을 다루는 시스템을 구축하는 경우라면, 이 책이 말하는 자유방임적인 자세가 불편할 수도 있습니다. 지나치게 경계하진 마세요. +
Getting Real은, 도입하지 않으면 폐기해야 하는 양자택일의 문제가 아닙니다. Getting Real을 열렬히 환영하진 않는다 해도, 감시자들의 눈을 피해 몇몇 아이디어를 적용해 볼 수는 있을 겁니다.

=== 당신들이 발명한 아이디어가 아니잖아요
우리는 이 아이디어들을 발명했다고 주장하지 않습니다. 이 책에서 언급하는 상당수의 개념들은 오랫동안 우리 주변에 어떤 형태로든 존재했습니다. 이 책을 읽다가, 누군가의 블로그에서 읽었거나 20년 전 책에서 읽은 것 같은 내용이 떠오르더라도 화내지 마세요. 충분히 있을 수 있는 일입니다. 이 책의 내용들은 37signals만의 아이디어가 아닙니다. 그저 우리가 어떻게 일해왔고, 어떤 방법들이 성공적이었는지를 말할 뿐입니다.

=== 지나친 흑백논리 아닌가요
우리가 잘난 척하는 것 같더라도 조금은 참아 주십시오. 우리는 적당히 얼버무리기보다는 대담하게 말하는 쪽이 좋다고 생각합니다. 그것이 간혹 건방지고 오만하게 보인다 하더라도 괜찮습니다. ‘경우에 따라’ 같은 말을 쓰기보다는 다소 도발적으로 표현하겠습니다. 물론 이런 규칙을 유연하게 적용해야 할 때도 있겠습니다. 그리고 어떤 전략은 여러분의 상황에 맞지 않을 수도 있습니다. 그럴 땐 스스로의 판단과 상상력을 동원하세요.


.Microsoft의 “Start.com” 출시
[TIP]
====
대기업에서는 프로세스와 회의가 당연한 절차다. 고객에게 옳은 것이 무엇인지에 대해 모두가 동의하기까지, 몇 달 동안 기능을 설계하고 세부 사항을 논의한다.
압축 포장된 소프트웨어에는 이런 방식이 잘 맞을지 모른다. 하지만 웹에서는 다르다. 그냥 출시해라! 무엇이 올바른지 그른지는 고객들이 말하도록 하자. 만약 올바르지 않다면 그날 바로 고쳐서 다시 출시해도 된다. 길고 지루한 회의와 논쟁에 사로잡히지 말자. 고객의 의견보다 더 중요한 것은 없다. 그냥 출시해서 의견을 증명해라.
말은 쉽지만 실행하기는 어려울 것이다. 이 말의 의미는 다음과 같다.

*수 개월짜리 계획은 필요 없다*

기초가 단단하고 세부 사항까지 계산되어 있으며, 개발 단계도 잘 나뉘어 있는 기술 명세를 작성하느라 몇 달을 허비하지 마라. 모든 문제(issues)를 해결하려고 하지도 말고, 개발을 시작하기 전에 모든 세부 사항을 다 정해두려고도 하지 마라.

*출시하는 기능을 줄이되, 품질은 검증하자*

수많은 기능을 포함시켜 완전히 새로운 버전을 출시하는 빅뱅 방법론(big bang approach)은 필요 없다. 고객이 소화할 수 있는 만큼만 전달하자.
사소한 버그 쯤은 놔두고, 핵심 기능에 초점을 맞춰 일단 출시한 다음에 수정해라. 사용자의 의견이 빨리 접수될 수록 더 좋다. 계획서에 적힌 아이디어는 대개 좋아보이지만, 구현을 하다 보면 더 좋은 아이디어가 나타나는 경우도 있다. 따라서 어떤 아이디어가 문제를 해결하는 데 적절하지 않다는 사실을 더 빨리 발견할수록 좋다.
사용자의 의견에 대해 대응이 빨라지기 시작하면, 사용자들과 관계가 구축된다. 기억하자. 사용자의 필요를 채움으로써 사용자를 확보하는 것이 목적이다.

사나즈 아하리(Sanaz Ahari), 마이크로소프트 Start.com의 프로그램 매니저
====

=== 우리 회사에는 적용할 수 없어요
Getting Real을 적용하기에는 회사가 너무 크다구요? 마이크로소프트도 Getting Real을 적용하고 있습니다(여러분의 회사가 마이크로소프트보다 크진 않을 거라고 확신합니다). +
비록 여러분의 회사가 전형적으로 큰 조직이고 긴 일정으로 운영하고 있더라도, Getting Real을 도입할 여지는 남아 있습니다. 우선은 큰 조직 안에서 Getting Real을 도입할 만한 작은 단위를 찾아내는 것입니다. 사람이 너무 많으면 아무것도 할 수가 없습니다. 몸집이 가벼울수록 업무를 더 빠르게 잘 수행할 수 있습니다. +
일종의 협상 능력이 필요할지도 모릅니다. Getting Real 프로세스를 여러분의 회사와 맞춰 가세요. 동료에게 이 책을 보여주고, 여러분이 짧은 시간에 작은 팀으로 성취할 수 있는 실제 결과를 보여 주세요. +
Getting Real이 적은 비용으로 부담 없이 시험할 수 있는 새로운 개념이라고 설명하세요. 진행 중인 큰 프로젝트에서 이 개념을 적용해서 효과를 증명할 만한 작은 부분이 있는지 살펴보고, 적용한 후에는 실제 결과를 보여주세요. +
여러분의 대담함을 증명하고 싶다면 그냥 몰래 진행하세요. 아무에게도 알리지 않은 채 무작정 진행한 다음, 실제 결과를 보여주는 겁니다. 마이크로소프트의 Start.com 팀도 이런 식으로 Getting Real을 적용했습니다. 마이크로소프트의 기술전도사(Technical Evangelist)인 로버트 스코블(Robert Scoble)은 “저는 Start.com의 팀워크를 지켜보았습니다. 그들은 승인을 요청하지 않습니다. 그들을 보호해 주는 상사도 있었습니다. 일을 작게 잘라내어 실행한 다음, 피드백을 받고 다시 처리합니다”라고 말했습니다.
