= 출발점 THE STARTING LINE
37signals
:doctype: article
:encoding: utf-8
:lang: ko
:toc: left
:numbered:

== 덜 하세요
=== 경쟁 상대보다 덜 하기
전통적으로 경쟁 상대를 이기려면 그들보다 하나를 더 하라고 합니다. 상대에게 네 가지 기능이 있다면, 여러분은 다섯 개(또는 열다섯 개나 스무 개)의 기능을 제공해야 합니다. 상대가 x만큼의 비용을 사용했다면, 여러분은 xx만큼을 사용해야 합니다. 그들이 20만큼을 가지고 있으면, 여러분은 30이 필요합니다. +
이러한 기능 늘리기 식의 냉전 체제는 끝났습니다. 비용이 많이 들고, 수동적이며 피해망상적인 개발 방식입니다. 수동적이고 피해망상에 사로잡힌 기업은 앞을 내다보지 못하고 뒤만 보게 됩니다. 업계를 이끌지 못하고, 누군가의 흉내를 낼 뿐입니다.

[NOTE]
====
만약 이런 기업을 만들고 싶다면,
지금 이 책을 덮어버리는 편이 낫습니다.
====

그러면 무엇을 해야 할까요? 대답은 “덜 하기(less)”입니다. 경쟁 업체보다 덜 만들어서, 그들을 이기는 것입니다. 간단한 문제를 해결하고, 복잡하고 까다로운 문제는 다른 이들에게 맡깁시다. 기능을 하나 늘리는 대신, 하나 줄여 보세요. 넘치게(outdoing) 하지 말고 모자라게(underdoing) 하세요. +
우리는 이 책 전체에 걸쳐 이 “덜 하기”의 개념을 소개하고 하였습니다. 하지만 일단 간단하게 설명해 보겠습니다.

* 기능 줄이기
* 옵션이나 설정 줄이기
* 인원 줄이기와 소규모 조직
* 회의 덜 하기와 개념 줄이기
* 약속 줄이기

== 무엇이 당신의 문제인가요?

=== 스스로를 위한 소프트웨어를 개발하자
소프트웨어를 개발하는 최상의 방법은 스스로의 문제를 해결하려고 하는 것입니다. 스스로가 고객이 되면, 무엇이 중요하고 무엇이 그렇지 않은지를 알 수 있습니다. 이 부분이 바로 두드러지는 제품을 만들 수 있게 합니다. +
여기서의 핵심은 여러분이 혼자가 아니라는 점입니다. 여러분에게 어떤 문제가 있다면, 비슷한 처지의 사람들이 수십만 명 정도 존재한다는 말입니다. 바로 여기에 여러분의 시장(market)이 있습니다. 간단하죠? +
Basecamp도 하나의 문제에서 시작했습니다. 37signals라는 디자인 회사는 프로젝트에 대해 고객들과 소통할 수 있는 간편한 방법이 필요했습니다. 처음에는 고객들이 접속할 수 있는 내부망(extranet)을 만들어 봤습니다. 그러나 HTML을 하나씩 수정하는 방식으로 프로젝트를 매번 업데이트했기 때문에, 제대로 돌아가지 않았습니다. 이러한 프로젝트 사이트들은 금새 녹슬어 갔고 결국엔 그만두게 되었습니다. 우리는 우왕좌왕했고 고객들도 소통을 못하는 상태에 머물러야 했기 때문에, 매우 낙심이 되었습니다. +
그래서 대안을 모색해 보았습니다. 우리가 찾아본 다른 도구들은 여전히 필요한 기능이 없거나 필요 없는 기능(예를 들면 과금, 어려운 접근 방법, 차트, 그래프 등) 투성이였습니다. 분명히 더 나은 방법이 있을 것 같았고, 그래서 우리가 만들기로 했습니다. +
스스로의 문제를 해결할 때, 여러분은 열정적으로 그 도구를 개발할 수 있습니다. 그리고 열정이야말로 핵심입니다. 열정이란 여러분이 정말로 사용하고 싶고, 신경 쓰고 싶다는 의미입니다. 그리고 다른 사람들에게도 그 열정을 전달하는 최고의 방법이기도 합니다.

.가려운 곳을 직접 긁어라
[TIP]
====
오픈 소스 진영에서는 오래 전에 이 진리를 깨달았다. 그들은 “가려운 곳은 직접 긁어라.”라고 얘기한다. 오픈 소스 개발자에게 이 말은, 그들이 원하는 도구를 그들이 원하는 방식으로  얻는다는 의미다. <<하지만 이익은 훨씬 커진다.>> +
여러분이 새로운 애플리케이션의 디자이너 혹은 개발자라면, 매일 수많은 일들을 결정해야 한다. 파란색을 쓸까 녹색을 쓸까? 표를 하나 넣을까 두 개 넣을까? 정적으로 구현할까 동적으로 구현할까? 중단할까 복구할까? 이럴 때 어느 쪽으로 결정하면 좋을까? 만약 중요한 사안이라면 누군가에게 물어볼 수라도 있다. 하지만 그 외의 일들은 결국 스스로 결정해야 한다. 그리고 이러한 결정들이 쌓여 애플리케이션에 ‘추측 덩어리(an interconnected web of assumptions)’라는 부채를 증가시킨다. +
개발자인 나는 이런 일을 싫어한다. 소프트웨어에 작은 시한 폭탄들이 존재한다는 사실이 내게 스트레스를 준다. 가려운 곳을 직접 긁는 오픈 소스 개발자라면 이러한 고통을 겪지 않는다. 스스로가 고객이기 때문에, 대다수의 결정을 올바르게 내릴 수 있다. 내 생각엔 이런 점 때문에 직장에서 열심히 코딩한 사람들이 집에 가서도 오픈 소스에 매달리는 것 같다. 긴장을 푸는 행위로서 말이다.

데이브 토머스(Dave Thomas)의 <실용주의 프로그래머>에서
====

.필요는 발명의 어머니
[TIP]
====
캠페인 모니터(Campaign Monitor)는 필요 때문에 태어났다. 몇 년 동안 우리는 이메일 마케팅 도구들의 낮은 품질 때문에 고생하고 있었다. 어떤 도구는 A와 B를 할 수 있었지만 C는 할 수 없었고, 또 다른 도구는 B와 C는 할 수 있었지만 A는 할 수 없었다. <우리는 결코 만족할 수 없었습니다.> +
그래서 우리는 일정을 모두 비운 후, 우리가 꿈꾸던 이메일 마케팅 도구를 만들어 보기로 했다. 우리는 다른 사람들이 도구를 어떤 식으로 사용하는지 조사하는 대신, 우리와 우리 고객의 삶이나마 조금이라도 편리해지는 도구를 만들기로 결정했다. +
제품을 다 만들자, 우리 말고도 기존 제품들에 만족하지 못하는 사람들이 많다는 사실을 알게 되었다. 그래서 다른 디자인 회사들도 사용할 수 있도록 소프트웨어를 조금 수정하였고, 입소문이 퍼지기 시작했다. 6개월이 지나기도 전에 수천 명의 디자이너들이 캠페인 모니터를 사용하여 고객들에게 이메일 뉴스레터를 발송하게 되었다.footnote:[(옮긴이) 번역하는 시점에 캠페인 모니터는 12만 명 이상의 사용자가 매 달 10억 건 이상의 메일을 발송하는 서비스가 되었다.]

http://www.campaignmonitor.com/[캠페인 모니터]의 창업자인 데이비드 그라이너(David Greiner)
====

.신중해져야 한다
[NOTE]
====
책을 쓰려고 한다면, 흥미로운 이야기 외에도 많은 것이 있어야 한다. 이야기를 하고 싶은 열정이 필요하다. 어떤 방식으로든 스스로에게 투자도 해야한다. 2년, 3년 혹은 여생을 무언가와 함께 살아야 한다고 생각해 보면, 신경을 꽤 써야할 테다.

말콤 글래드웰(Malcolm Gladwell), http://www.powells.com/authors/gladwell.html[‘A Few Thin Slices of Malcolm Gladwel’ 인터뷰]에서
====

== 스스로 투자하라

=== 투자 유치는 차선책이다
많은 스타트업들이 최고 우선순위에 두는 일은 바로 대부분 투자자에게 투자를 유치하는 것입니다. 하지만 외부 자금을 받으면, 그들에게 답을 줘야만 합니다. 기대는 커지고, 투자자는 서둘러서 투자금을 회수하고 싶어 합니다. 슬프게도 이러한 일들이 제품의 품질을 가로막기 시작합니다. +
요즘엔, 일을 시작할 때 그렇게 많은 자금이 필요하지 않습니다. 하드웨어는 저렴하고, 수많은 훌륭한 오픈 소스 인프라 소프트웨어를 무료로 구할 수 있습니다. 무엇보다도 열정에는 가격표가 딸려 있지 않습니다. +
그러니까 여러분이 가진 돈으로 할 수 있는 정도만 실행하세요. 깊이 생각해서 무엇이 정말로 필수적인지 혹은 없어도 되는지 결정하세요. 열 명이 아닌 세 명이라면 무엇을 할 수 있을까요? 1억 원이 아닌 2천만 원으로는 무엇을 할 수 있을까요? 6개월이 아닌 3개월 동안엔 무엇을 할 수 있을까요? 직장에 다니면서도 사이드로 애플리케이션을 만들려면 어떻게 하면 좋을까요?

=== 제한된 환경이 창조성을 유발합니다
한정된 자원으로 일을 하다 보면, 초기부터 압박감을 매우 강하게 느끼게 됩니다. 그리고 이것은 좋은 현상입니다. 제한된 환경이 혁신을 불러 일으킵니다. +
또한 제약은, 아이디어를 미루지 않고 보다 빠르게 내놓을 수 있게 만드는 장점이 있습니다. 출시 후 1-2개월 안에 뛰어난 아이디어였는지 여부가 판가름 납니다. 만약 맞다면 여러분은 당분간 외부 자금 없이도 유지할 수 있을 겁니다. 아이디어가 형편 없다는 것으로 판명되면, 계획을 다시 세워야 합니다. 어느 쪽이든, 수 개월 혹은 수 년 후가 아닌 한두 달 안에 그 사실을 알게 됩니다. 그리고 쉽게 되돌아올 수도 있습니다. 하지만 투자자가 끼어들기 시작하면, 출구 전략(exit plan)은 더욱 요원해집니다. +
돈을 쉽게 벌어보려는 목적으로 소프트웨어를 만든다면, 금방 티가 납니다. 빠른 고수익이 불가능하다는 말은 사실입니다(Truth is a quick payout is pretty unlikely). 그러니까, 여러분이나 고객들이 오랫동안 사용할 수 있는 좋은 도구를 만드는 데 집중하세요.

.두 가지 방법footnote:[(엮은이) 제이크 워커(Jake Walker)는 투자를 받아 Disclive라는 회사를 설립했고, 투자 없이 The Show라는 회사도 설립했다. 이 둘의 차이가 무엇인지 들어보자.]
[TIP]
====
모든 문제의 근원은 투자금 자체가 아니고, 돈과 함께 딸려오는 것들이다. 기대는 정말 높다. <<직원들이 급여에 대해 이야기하기 시작하고, 회사를 키워서 팔아치우는 것이 동기가 되고, 혹은 초기 투자자의 투자금을 돌려주기 위한 방법을 찾아야 했다.>> Disclive에서는 우리 자신을 그야말로 부풀리기 시작했다. 마지 못해 말이다. +
The Show에서는, 시간만 더 들인다면 적은 비용으로도 더 나은 제품을 만들 수 있음을 깨달았다. 그리고 좋은 제품이라면 고객들이 어느 정도 기다려 줄 거라는 데 우리가 가진 돈을 걸어 보았다. 회사는 계속 작은 규모로 유지하기로 했다(앞으로도 계속 그렇게 할 생각이다).  첫 프로젝트 이후에도 우리는 계속 외부 자금 없이 운영하고 있다. 관련 업체들과 조금 창의적인 계약 방식을 택하여, 그다기 큰 돈이 들 일이 없기도 했다. 회사를 키워서 팔 정도는 되지 않았지만, 사업을 계속 할 정도의 이윤을 내고 있고 성장도 하고 있다.footnote:[(옮긴이) 번역하는 시점에 Disclive와 The Show는 모두 사라졌고, 제이크 워커는 보스턴에서 변호사로 살아가고 있다.]

http://goo.gl/1t05eS[Signal vs. Noise 블로그에 달린 댓글]footnote:[(옮긴이) http://goo.gl/1t05eS] 중에서
====

== 일정과 예산은 고정, 범위는 유연하게

=== 예산과 일정 범위 내에서 완료하세요
일정과 예산 범위 내에 프로젝트를 완료하는 간단한 방법을 소개합니다: 결정된 것을 지킨다. 문제에 대해서는 시간이나 돈으로 해결하지 말고, 단지 범위를 축소한다.
이런 전설이 있습니다. : 우리는 일정, 예산, 범위 내에 완료할 수 있다. 하지만 이것은 품질을 떨어뜨리지 않고는 불가능하다. +
모든 것을 계획된 일정과 예산안에서 해결할 수 없다 하더라도, 절대로 일정과 예산을 늘리지 말고 범위를 축소시키세요. 향후 이러한 기능을 포함시킬 시간은 언제든지 있습니다. 나중은 끝없이 영원하고 지금은 쏜살 같이 지나갑니다. +
비현실적인 마법 같은 시간, 예산, 범위로 헛점투성이의 싸구려 결과물을 만드는 것보다도 계획보다 범위가 축소되어 보다 작게 시작하는 것이 낳습니다. 그런 마법은 마술사 후디니(역주: 세계최고의 탈출 마술사, 1874-1926)에게나 맡기세요. 제대로 된 제품을 시장에 공급하는 것이 현실 세계의 비즈니스입니다.
시간과 예산을 고정시킴으로써 얻을 수 있는 효과에 대해서 알아보겠습니다.

* 우선 순위
무엇이 정말로 중요한 것인가를 파악해야 합니다. 최초 출시를 위해 무슨 기능의 제품을 만들고 있습니까? 이러한 제약은 당신으로 하여금 쓸데없는 것 대신 명백한 결정을 할 수 있도록 있게 해줍니다.

* 현실성
기대치를 정하는 것이 중요합니다. 만약 시간, 예산 및 일정을 조정한다고 해도, 고품질의 제품을 출시할 수 없을지 모릅니다. 물론 무엇인가를 출시할 수도 있습니다만 정말 그렇게 출시하고 싶으십니까?

* 유연성
변화관리 능력도 중요합니다. 한번 결정된 것들은 변경하기가 어려워집니다. 유연성의 요소를 가미시켜 제품 개발 시 경험에 근거한 옵션이 도출되도록 합니다. 유연성은 당신의 친구입니다.

우리가 추천하고자 하는 것은: “범위를 축소시켜라”고 하는 것입니다. 그것이 비록 반쪽 기능의 제품이라도, 형편없는 전체 기능의 제품보다는 낫습니다. (뒷장에서 자세하게 설명하겠습니다.)

.1, 2, 3 ...
[NOTE]
====
프로젝트가 예정보다 1년이나 지연되었을 땐 어떻게 할까요? 하루에 하나씩 차근차근 해보세요.

소프트웨어 엔지니어이자 컴퓨터 공학가인 https://ko.wikipedia.org/wiki/%ED%94%84%EB%A0%88%EB%8D%94%EB%A6%AD_%EB%B8%8C%EB%A3%A9%EC%8A%A4[프레드 브룩스(Fred Brooks)]
====


== 경쟁 상대를 만드세요

=== 맞서 싸우세요
여러분의 애플리케이션이 어떤 모습이어야하는지 알아내는 최선의 방법은 반대로 생각하는 것입니다. ‘어떤 모습이 되어서는 안 될까?’입니다. 경쟁 상대의 애플리케이션을 분석하면, 여러분이 가야 할 방향을 알게 될 겁니다.
37signals에서 사용하기엔 마이크로소프트사의 프로젝트(Project) 소프트웨어가 작은 방 속의 고릴라처럼 너무 비대했기 때문에, 우리는 프로젝트 관리 도구를 새롭게 개발하기로 결정했습니다. 고릴라에 맞서는 두려움 대신, 이것을 동기 부여의 기회로 이용했습니다. Basecamp는 MS Project에 맞서 완전히 색다른 도구가 되어야 했습니다. +
우리는 프로젝트 관리가 차트나 그래프, 보고서, 통계치에 대한 것이 아닌, 바로 ‘커뮤니케이션’이라는 사실을 포착했습니다. 또한, 프로젝트 관리란 높은 자리에 앉은 프로젝트 매니저가 프로젝트 계획을 일방적으로 알리는 것도 아니었습니다. 프로젝트 관리란 프로젝트가 완성되게 하려고 모두가 각자의 책임을 기꺼이 떠맡는 것이었습니다.
단 하나의 적은, 프로젝트 관리자와 그가 휘두르는 채찍이었습니다. 그래서 우리는 프로젝트 관리 분야를 민주화하고 싶었습니다. 고객을 포함하여 모든 관계자가 참여할 수 있게 말이죠. 프로젝트의 각 과정에 모든 사람이 주인 의식을 가질 때,  프로젝트는 더 좋아졌습니다. +
WriteBoard를 만들 때도, 경쟁 상대들이 이미 화려한 기능들을 많이 포함하고 있는 사실을 알았습니다. 그래서 우리는 오히려 요란하지 않다는 점을 강조하기로 결정했습니다. 불필요한 기능은 버리고, 사람들이 아이디어를 공유하고 협업할 수 있는 간단한 애플리케이션을 개발했습니다. 그리고 서비스 출시 3개월 만에 십만 개가 넘는 Writeboard가 만들어졌습니다. +
Backpack을 개발할 때는 우리의 적이, 구조와 경직된 규칙이었습니다. 사용자들이 자신만의 방식으로 정보를 자유롭게 정리할 수 있어야 하며, 정형화된 화면이나 과다한 필수 입력 폼을 요구하지 않으려 했습니다. +
경쟁 상대가 있을 때 또 하나의 이점은, 마케팅에서 전달하려는 메시지가 매우 분명해진다는 것입니다. 사람들은 승부에 열광합니다. 사람들은 경쟁 제품들을 비교하면서 제품을 이해합니다. 경쟁 상대를 정해서, 사람들이 원하는 이야기를 만들어 낼 수 있습니다. 그러면 사람들은 제품을 더 잘 이해하는 단계를 넘어서, 제품의 팬이 될 것입니다. 이것이야말로 이목을 집중시키고 열정에 불을 붙이는 가장 확실한 방법입니다. +
하지만 경쟁만을 의식하지는 않아야 합니다. 다른 제품을 분석하는 데만 집중하다 보면, 생각이 틀에 갇히게 됩니다. 살펴본 다음에는 여러분만의 관점과 여러분만의 아이디어로 옮겨가세요.

.앞선 이를 따르지 마라
[NOTE]
====
마케터들(그리고 모든 사람들은)는 앞선 이를 따라서 하라고 훈련받습니다. 사람의 본성은,  경쟁 상대의 강점을 알아내어 그것을 이기려 합니다. 그들의 강점이 속도이면 더 빨리 한다든가,  그들이 강점이 가격이면 더 싸게 공급하듯이 말이죠.  문제는,  한 소비자가 이미 누군가의 이야기를 듣고,  그 거짓말을 믿었다면, 그 소비자를 설득하는 일은 소비자 스스로 틀렸음을 인정하도록 설득하는 일과 같습니다.  그리고 사람들은 자신이 틀렸다고 인정하기를 싫어합니다. +
대신, 여러분은 전혀 다른 이야기를 해서, 여러분이 들려주는 이야기가 다른 이들의 이야기보다 더 중요하다고 믿게 만들어야 합니다.  경쟁 상대의 강점이 속도라면 여러분은  싼 가격으로 승부해야 합니다. 경쟁 상대가 건강을 이야기하면, 여러분은 편리함을 이야기해야 합니다. 복잡한 그래프를 그려 놓고 “우리가 더 저렴합니다.”라고 외치지 말고, 그들이 들었던 이야기와는 전혀 다른, 진짜 이야기를 해주세요.

http://sethgodin.typepad.com/[세스 고딘(Seth Godin)]의 http://money.cnn.com/magazines/fsb/fsb_archive/2005/05/01/8259747/[‘Be a Better Liar’]에서
====

.무엇이 진짜 문제인가
[NOTE]
====
문제에 빠져드는 가장 빠른 방법은 바로 경쟁 상대가 뭘 하고 있는지 살펴보는 것입니다. 이것은 특히 우리가 만든 BlinkList 서비스에 대해서 진실이었습니다. 우리가 서비스를 시작했을 때는 이미 십여 개나 되는 소셜 북마크 서비스가 존재했습니다. 어떤 사람은 자세한 비교표를 만들어 올리기도 했죠.
이런 상황에서는 자칫 길을 잘못 들 수 있습니다. 그래서 우리는 큰 그림에 집중했고, 계속해서 스스로에게 물어 보았습니다. “우리가 해결하려는 문제는 무엇이고,  이 문제를 어떻게 해결할 것인가?”라고 말이죠.

http://www.mindvalley.com/[MindValley] & http://www.blinklist.com/[Blinklist]의 공동 창업자인 마이클 레이닝(Michael Reining)
====

== 잡일을 만들지 마세요

=== 당신의 열정 혹은 열정 부족함이 길을 비추리라
The less your app is a chore to build, the better it will be.  애플리케이션이 작을수록 해야 하는 일도 작아집니다. 그 과정을 즐기고 싶다면, 작고 관리 가능할 정도로만 유지하세요. +
만약 여러분의 애플리케이션이 여러분을 더이상 흥분시키지 않는다면, 뭔가 문제가 있는 것입니다. 단지 돈을 벌기 위해서 일을 하고 있다면, 금방 표시가 날 겁니다. 반대로, 여러분의 애플리케이션에 열정을 느낀다면 이 역시 최종 결과물에 묻어납니다. 사람들은 두 차이를 바로 느낄 수 있습니다.

.열정
[NOTE]
====
디자인에서는 어떤 의미들은 대단히 주관적이고 애매모호하지만, 열정이 담겼는지만큼 분명하고 알기 쉽게 드러나는 것도 드뭅니다. 제품 디자인은 여러분에게 흥미를 갖게 하거나 시시함을 안겨주거나 둘 중 하나일 뿐입니다. 두 경우 모두 제작에 들어간 노력을 예측하기란 어렵지 않습니다.
열의가 당연하게 드러나듯이, 냉담함 역시 지워지지 않습니다. 진짜 열정에 싸여 일을 추진하지 않았다면, 아무리 정성들여 만든 매력적인 디자인이라 해도 그 안에 있는 공허함은 숨길 수 없습니다.

http://www.subtraction.com/[Subtraction.com]의 코이 빈(Khoi Vinh)
====

.빵집
[NOTE]
====
지금의 미국식 비즈니스는 아이디어를 개발하고, 수익성 있게 만들고, 그 수익성을 판매한 다음, 사업을 확장하거나 다각화하는 것입니다. 죄다 이렇게들 하고 있습니다. 반면 제 아이디어는 이렇습니다. 즐겁게 빵을 구워, 사람들에게 팔고, 사람들이 빵을 좋아하면 더 많이 팝니다. 계속 좋은 음식을 만들면 사람들은 행복해지고, 빵집은 계속 유지할 수 있습니다.

Fugazi 밴드의 멤버이자 Dischord 레코드의 공동 소유자인
이언 맥케이(Ian MacKaye)의 http://www.salon.com/2001/01/08/mackaye/[Salon.com 인터뷰]에서
====
