= 날렵함 유지하기 STAY LEAN
37signals
:doctype: article
:encoding: utf-8
:lang: ko
:toc: left
:numbered:

== 더 작은 규모
=== 가벼울수록, 변화하기가 쉬워집니다
사물이 크면 클수록, 그 방향을 바꾸는 데 막대한 에너지가 필요해 집니다. 이것은 물리 세계 뿐만 아니라, 비즈니스 세계에도 적용되는 사실입니다. +
웹 기술 세상에서, 변화는 더 쉽고 저렴해야만 합니다. 만약 그럴 수 없다면, 그럴 수 있는 누군가에게 자리를 양보하게 될 것입니다. 만약 변화의 스피드를 따라갈 수 없어지면, 다른 누군가가 그것을 가로채갈 것 입니다. 이것이 작은 규모를 추구해야 하는 이유입니다.

=== 규모가 커지는 요소
* 장기간 계약
* 너무 많은 직원
* 영구적인 결정
* 회의에 대한 회의
* 경직된 프로세스
* 재고(물리적이거나 정신적인)
* 소프트웨어, 하드웨어, 기술의 종속성
* 독점 형태의 데이터 포맷
* 과거에 정해진대로만 하는 미래
* 긴 로드맵
* 사내 정치

=== 규모가 작아지는 요소
* 적절한 고민
* 팀원의 멀티태스킹
* 제약사항 파악 (제약사항 제거가 아님)
* 작은 소프트웨어, 적은 코드
* 적은 기능
* 작은 팀 규모
* 단순함
* 절제된 인터페이스
* 오픈 소스 제품
* 공개된 데이터 포맷
* 실패를 인정해주는 개방적인 문화

규모가 작으면 방향을 신속하게 변경할 수 있습니다. 반응하고 진화할 수 있습니다. 좋은 아이디어에만 집중할 수 있고, 나쁜 아이디어는 버릴 수 있습니다. 고객의 소리에 귀를 기울일 수 있고, 응답할 수도 있습니다. 새로운 기술을 나중에 도입하는 대신, 지금 바로 도입할 수 있습니다. 항공모함이 아닌, 쾌속선으로 항해하세요. 이러한 사실을 즐기세요. +
상상해봅시다. 기능이 단촐한 작은 소프트웨어를 만드는 날렵한 소규모 회사를 말이죠. 다른 쪽에는 기능이 엄청나게 많은 소프트웨어를 판매하는 대기업이 있고요. 자 이제, Ajax 같은 새 기술이나 태그 같은 새로운 개념이 등장합니다. 어느 쪽이 더 빨리 제품에 적용할 수 있을까요? 1년짜리 출시 로드맵 안에서 더 많은 기능을 포함한 거대 소프트웨어를 만드는 팀과, 기능을 줄인 작은 소프트웨어를 만들면서 "지금 당장 우리가 주목해야 할 일에만 집중하자"라고 말하는 유기적인 팀 중 어느 쪽이라고 생각하십니까? +
소규모 회사 쪽이 시장의 요구에 민감하게 반응할 수 있음은 분명합니다. 작은 회사가 방향을 전환한 다음에도, 대기업은 방향을 바꿔야 하는지 계속 토론하거나 관료적인 절차를 한참이나 거칠 겁니다. 대기업이 어떻게 걸어가야할지 계획하는 동안, 소규모 회사는 두세 발 앞서 갈 수 있습니다. +
재빠르고 날렵한 작은 비즈니스라면, 비즈니스 모델, 제품, 기능, 마케팅 전략 등 모든 것을 재빨리 바꿀 수 있습니다. 실수도 하겠지만 재빨리 고칠 수도 있습니다. 또한 우선 순위나 제품군, 집중할 분야 등도 바꿀 수 있습니다. 그리고 가장 중요한 것은 *스스로의 마음가짐도 바꿀 수 있다는 점입니다.*

== 변화에 따른 비용을 적게 하세요
=== 변화의 장애를 줄여서 유연하게 대처하세요.
변화는 당신에게 있어서 최고의 친구입니다. 변화의 비용이 많이 들수록, 그만큼 그것을 완수하기 힘들어집니다. 그리고, 경쟁 상대가 보다 빠르게 변화한다면, 당신은 매우 불리한 입장에 놓여집니다. 변화가 너무 많은 이용을 요구하게 되면, 그것은 곧 죽음을 의미합니다. +
이러한 것 때문에 군살을 빼는 것의 진가가 발휘됩니다. 만원으로 변화를 완수하는 능력은, 작은 팀에서는 기본적으로 가능한 것으로써, 큰 조직에서는 결코 불가능한 일입니다. 이런 이유로 큰 것이 작은 것을 시기 합니다. 거대한 조직에서의 거대한 팀이 몇 주 걸리는 것을 작은 조직에서는 불과 하루 만에 가능합니다. 이러한 장점은 가격을 매길 수 없습니다. 저비용으로 신속한 변화가 가능하다는 것은 숨은 병기와도 같습니다.

[NOTE]
====
기억하세요: 작기 때문에 가능한 민첩성은 세상의 모든 돈이나 마케팅, 사람으로 얻을 수 없는 것입니다.
====

그리고 웹 기반 기술에서의 변화는 쉽고 저렴해야 합니다. 변혁은 간단하고 싸지 않으면 안됩니다. 만약 재빠르게 변화할 수 없다면, 다른 사람이 치고 올라옵니다. 이것이 작은 규모를 유지해야 하는 이유입니다.

.Emergence
[TIP]
====
Emgergence 는 기민함의 기본 원리이며, 마법의 원리 중에 하나입니다. Emergence의 특징들은 미리 계획되거나 디자인되는 것이 아닙니다. 그것들은 전체 시스템의 다양한 결과에 의해서 자연스레 나타나게 됩니다. “Emergence”라는 말은 17세기의 라틴어로 “예측되지 않은 발생”이라는 뜻입니다. 우리는 그것을 예측허가나 계획할 수 없으며, 다만 그러한 발생이 가능한 환경을 만들 수 있을 뿐입니다. +
Emergence의 전형적인 예는 떼를 지어 날아가는 새들에서 찾을 수 있습니다. 컴퓨터 시뮬레이션에서는 3개의 간단한 규칙만 사용해서 새들이 목적지로 날아가는 동안 장애물 피한 후에 따시 전열을 갖추는 등의 복잡한 행동들을 구현할 수 있습니다. 이러한 고도의 동작들은 그것에 대한 정해진 규칙이 있는 것이 아니며, 전체 시스템에 의해서 역학적으로 발생(emergence)하는 것입니다. +
새들의 시뮬레이션에서와 같이 간단한 규칙들이 복잡한 행동을 이끌어 냅니다. 반면에 복잡한 규칙들은 어리석은 행동을 유발합니다. 많은 나라의 복잡한 세법들이 그러한 예입니다. +
소프트웨어 개발에서의 많은 관례들은 불행하게도 Emergence가 발생할 가능성을 제거하는 부작용을 가지고 있습니다. 최적화를 위한 많은 노력들은 Emergence의 발생에 있어 가장 중요한 상호작용과 관계들의 범위를 줄여버립니다. 떼를 짓는 새들의 예에서도 흥미롭고 유용한 행동을 만들어 내는 것은 새들간의 관계와 상호작용입니다. +
우리가 일들을 고정하고 단단히 묶어버릴 수록 창의나 Emergence가 발생할 여지는 줄어들게 됩니다. 잘 이해하지 못한 상태에서 요구사양을 확정지어버리거나 너무 이른 시점에 코드를 최적화하려고 하거나, 고객이 시스템을 사용해보기도 전에 복잡한 네비게이션이나 워크플로우를 만들고 고정해버리는 것들이 그러한 예입니다. 그 결과는 불필요하게 복잡하고 멍청한 시스템이 될 것이며, Emergence가 발생할 수 있는 깔끔하고 우아한 시스템은 결코 될 수 없습니다. +
작게 유지하세요. 단순하게 유지하세요. 이루어지게 하세요.

앤디 헌트, <실용주의 프로그래머>에서
====

== 삼총사
=== 버전 1.0은 3명의 팀에서 개발 해라.
애플리케이션의 최초의 버전은 단지 3명만으로 시작하세요. 그것이 당신이 능률적이고 민첩하게 계속 되게 해주는 맨파워를 부릴 수 있는 마법의 숫자입니다. 개발자와 디자이너와 스위퍼 (Sweeper, 두 세상을 조율해 줄 수 있는 사람)로 시작하세요.

소수 인원수만으로 애플리케이션을 구축하는 것은 분명한 도전입니다. 그러나 올바른 팀을 가지고 있다면, 그것은 가치 있는 일입니다. 능력이 있는 사람에게는 끝없는 자원은 필요 없습니다. 그 사람들은 제한적인 환경에서도 도전적인 과제들을 성공시키며, 창조성으로 문제를 해결합니다. 일손이 부족하다고 하는 것은, 프로세스의 초기에 있어 무엇인가 거래를 해야 하는 의미를 내포하고 있지만 문제 될 것이 업습니다. 그것은 당신에게 나중보다는 먼저 해야 할 우선순위를 생각하게 합니다. 그리고 당신은 정기적으로 동료의 걱정을 없애기 위해 커뮤니케이션을 하게됩니다..

만약 당신이 첫 번째 버전을 세 사람이 구축할 수 없으면, 추가 인력이 필요한가 아니면 최초 버전의 규모를 축소해야 하는가를 생각하게 됩니다. 최초 버전은 작고, 타이트에서도 상관없다는 것을 기억하세요. 당신의 아이디어에 날개가 있을지 어떨지는 곧바로 압니다. 그렇게 함으로써, 명료하고 심플한 기반의 제품을 가질 수 있습니다.

.메트칼프의 법칙(Metcalfe’s Law)과 프로젝트 팀
[TIP]
====
팀은 가능한 한 작게 유지하세요. “커뮤니케이션 시스템의 가치는 그 시스템의 유저수의 제곱으로 증가한다”는 Metcalfe’s Law(매트칼프 법칙)도 프로젝트 팀에 대해서도 적용됩니다. 팀의 효율성은 팀 내의 멤버의 수의 제곱에 반비례 합니다. 1.0 의 제품의 출시에는 3명이 최적이라고 생각합니다. 당신은 팀에 가세하려고 한 사람들의 수를 줄이는 것부터 시작하세요. 그리고 한층 더 여러 명 줄이는 겁니다.

Marc Hedlund, O’Reilly Media기업가
====

.커뮤니케이션 흐름
[TIP]
====
커뮤니케이션은 큰 팀보다는 작은 팀에서 잘 통용됩니다. 만약 당신이 프로젝트에 있어서의 유일한 사람이라고 하면, 커뮤니케이션은 간단합니다. 유일한 커뮤니케이션 경로는 당신과 고객입니다. 프로젝트에 관련되는 사람의 수가 증가할 수록, 커뮤니케이션의 경로도 증가합니다. 그것은 사람의 수가 증가함에 따라서 가산되어 가는 것은 아닌, 사람의 수의 제곱에 비례해 배로 증가해서 갑니다.

Steve McConnell, Chief Software Engineer at Construx Software Builders Inc.
(from Less is More: Jumpstarting Productivity with Small Teams)
====

== 제한을 수용한다
제한을 창조적 해결책으로 승화하세요.
세상에 있는 것은 결코 충분하지는 않습니다. 시간도 돈도 사람도 충분하지 않습니다. +

_그것은 좋은 일입니다._

이러한 제약사항으로 흥분하지 말고, 받아 들이세요. 제약사항은 창조와 초점에 집중하도록 해줍니다. 제약 사항을 없애려 하지 말고, 그것을 당신에게 유리하게 이용하세요. +
37signals의 경우도 “Basecamp” 개발시에 많은 제약이 있었습니다. 그것은：

* 운영 디자인 회사 결정
* 기존의 고객과의 일
* 7시간의 시차(프로그래머 David은 덴마크에서 개발하고 있었고, 나머지는 미국에서 있었습니다.)
* 작은 팀
* 외부 조달 투자가 없는 상태

우리는, “충분하지 않다”라고 투덜대고 있었습니다. 우리는 그릇을 작게만 하고 있었습니다. 작은 그릇은 담을 수 있는 양도 정해져 있습니다. 우리는 큰 태스크를 작은 단위로 쪼갠 후 한번에 한 개씩 실행 했습니다.. 사전 우선순위를 결정한 대로 단계별로 해결해 나갔습니다. +
그것은 우리로 하여금 창의적인 제품을 개발할 수 있게 해주었습니다. 언제나 작은 규모로 소프트웨어를 개발하여 우리는 변경 비용을 낮췄습니다. 사람들에게 스스로의 문제를 스스로의 방법으로 해결하는데 충분한 특징을 도입해, 그들에게 맡겼습니다. 우리들 내부의 시차와 거리의 문제는 커뮤니케이션을 함에 있어 보다 효율적으로 할 수 있게 해주었습니다. 사람과의 미팅 대신에, 대부분 메신저와 전자메일로 커뮤니케이션 하였으며, 이것이 우리의 문제에 대해 빠르게 집중할 수 있었습니다. +
제약사항은 가끔씩은 우리에게 장점이 됩니다. 벤처캐피털, 긴 제품 출시 일정, 고용은 잊어버리고, 가지고 있는 자원으로 일에 전념하세요.

.해충과 싸우세요
[TIP]
====
“Creeping elegance”(프로그래머들이 지나치게 고상함에 집착하여 소프트웨어의 기능성이나 스케쥴, 사용성을 다소 무시하는 현상)는 “기능 해충”으로 표현하는 것이 더 적절할 지도 모릅니다. 이것은 식물의 진액을 빨아먹고식물 전체를 서서히 망가뜨리는 곰팡이와 같습니다. 소프트웨어에서 기능 해충을 방지하는 가장 쉬운 방법은 물론 데드라인을 압박하는 것입니다. 데드라인에 대한 압박은 구현이 오래 걸리는 기능들을 제외하게 만듭니다. 하지만 일반적으로는 가장 중요한 기능이 구현하는 데 시간도 가장 오래걸립니다. 따라서 기능 해충과 데드라인의 조합은 중요하지 않은 기능들로만 가득찬 소프트웨어라는 결과를 만들게 되므로 주의해야 합니다.
—Jef Raskin, 저자 (http://jef.raskincenter.org/unpublished/widgets_of_the_week.html#anchor1152335[“Why Software Is the Way It Is”]에서)
====

== 있는 그대로
=== 대기업과는 다른 사람의 마음을 생각한 친밀감 있는 방법으로 접근하세요.

많은 작은 기업들이 스스로를 크게 보이게 하려고 행동하는 실수를 합니다. 스스로 작은 규모를 극복 해야할 약점으로서 생각하는 것 같습니다. 안타깝습니다. 작은 것은 큰 무기입니다-특히 커뮤니케이션의 부분에서는 더 그렇습니다. +
작은 회사는 격식이 적고, 관료적인 것이 덜하고, 보다 자유롭습니다. *기본적으로 작은 회사는 고객과 가까운 위치에 있습니다.* 그것은 고객과 직접 개개인에 접근 할 수 있는 방법으로 커뮤니케이션이 생기는 것입니다. 만약 작은 조직이라면, 까다로운 전문 용어를 사용하지 않고 더 친밀한 말로 이야기를 할 수 있습니다. 당신의 사이트나 제품은 기업의 선전문구가 아닌, 인간의 메시지를 전할 수 있습니다. 작은 규모라는 것은 고객을 깔보는 것이 아닌 고객과 대화할 수 있는 것입니다. +
작은 회사에서는 조직 내부의 커뮤니케이션에도 장점이 있습니다. 무엇인가의 서류에 좌지우지되지 않고, 쓸데없이 복잡한 프로세스나 여기저기의 승인 도장도 필요 없게 됩니다. 어느 과정에서도 멤버 전원이 오픈 마인드로 정직하게 이야기할 수 있습니다. 아이디어에 속박이 없는 흐름은, 작은 규모의 큰 이점의 하나입니다.

.당당히 정직하게
[TIP]
====
어쩌면 소비자는, 기업의 종업원수나 제품의 수, 즉 기업의 규모를 과장하면 속아 버릴 것이라고 생각할지도 모릅니다만, 영리한 사람(즉 당신이 정말로 타켓으로 하고 싶은 사람)은, 언제나 진실을 압니다. 창피한 이야기입니다만, 저도 과거에 이러한 자신을 크게 보이려고 했던 한 명입니다. 그러나, 그러한 일을 해도, 비즈니스가 의미 있는 것이 되어, 스스로의 서비스를 정말로 필요로 하고 있던 고객과의 관계가 계속 되어 신뢰 깊은 관계가 생긴 일은 없었습니다. 결국, 회사의 실제의 규모가 작아도 부끄러워하는 않고, 솔직하게 말하면 좋습니다.

Khoi Vinh, Subtraction.com
====

.언제라도
[TIP]
====
고객에게 있어서 좋은 고객 서비스는 어떤 비즈니스든지 최대의 기대사항입니다. 우리 조차도 그것을 바라는데, 고객은 어떻겠습니까? 초창기부터 우리에게 문의하는 모든 고객 및 모든 질문에 투명하게 대응했습니다. 웹 사이트에서는 무료 전화 번호를 기재하여, 우리 휴대폰으로 오게 했고, 명함에도 각자의 휴대폰 번호를 기재했습니다. 우리는 고객에게 무슨 일이 일어나든지 우리에게 연락할 수 있다고 강조했습니다. 고객들은 이러한 신뢰에 대해 고마워했고, 이 서비스에의 클레임은 없습니다.

Edward Knittel, Director of Sales and Marketing, http://www.kennelsource.com/[KennelSource]
====
